name: Build Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: tag_release
    steps:
      - uses: actions/checkout@v3
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ${{ secrets.REGISTRY_URL }}/public-apis:latest
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          cache: false